In [ ]:
#https://towardsdatascience.com/linear-regression-on-boston-housing-dataset-f409b7e4a155

In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
from sklearn.datasets import load_boston
boston_dataset = load_boston()

boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names, dtype = "float32")
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM        AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.199997  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.900002  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.099998  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.799999  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.200001  6.0622  3.0  222.0   

     PTRATIO           B  LSTAT  
0  15.300000  396.899994   4.98  
1  17.799999  396.899994   9.14  
2  17.799999  392.829987   4.03  
3  18.700001  394.630005   2.94  
4  18.700001  396.899994   5.33

In [3]:
boston['MEDV'] = boston_dataset.target

In [4]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM        AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.199997  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.900002  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.099998  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.799999  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.200001  6.0622  3.0  222.0   

     PTRATIO           B  LSTAT  MEDV  
0  15.300000  396.899994   4.98  24.0  
1  17.799999  396.899994   9.14  21.6  
2  17.799999  392.829987   4.03  34.7  
3  18.700001  394.630005   2.94  33.4  
4  18.700001  396.899994   5.33  36.2

In [5]:
boston['MEDV'].dtypes

dtype('float64')

In [6]:
input = boston.drop(["MEDV"], axis=1)
input.head()

input = torch.tensor(input.values)

In [7]:
target = boston["MEDV"]
target.head()

target = torch.tensor(target.values)

In [8]:
w = torch.randn(input.shape[0],input.shape[1], requires_grad=True)
b = torch.randn(input.shape[0], requires_grad=True)

In [9]:
def model(x):
    return x @ w.t() + b

In [10]:
prediction = model(input)
print(prediction)

tensor([[ -341.9097, -1127.5944,  -640.8036,  ...,  -347.7625,  -720.1273,
          -307.4921],
        [ -268.1095, -1048.9822,  -576.6728,  ...,  -408.2997,  -680.1852,
          -318.6597],
        [ -265.0633, -1019.9161,  -598.1678,  ...,  -412.8164,  -682.5749,
          -301.1330],
        ...,
        [ -335.8627, -1111.5605,  -584.5121,  ...,  -350.5003,  -673.3894,
          -330.5874],
        [ -335.4149, -1105.5004,  -584.3912,  ...,  -346.7873,  -667.8843,
          -326.4912],
        [ -325.7050, -1103.7996,  -602.4075,  ...,  -364.2811,  -680.4476,
          -318.3993]], grad_fn=<AddBackward0>)


In [11]:
print(target)

tensor([24.0000, 21.6000, 34.7000, 33.4000, 36.2000, 28.7000, 22.9000, 27.1000,
        16.5000, 18.9000, 15.0000, 18.9000, 21.7000, 20.4000, 18.2000, 19.9000,
        23.1000, 17.5000, 20.2000, 18.2000, 13.6000, 19.6000, 15.2000, 14.5000,
        15.6000, 13.9000, 16.6000, 14.8000, 18.4000, 21.0000, 12.7000, 14.5000,
        13.2000, 13.1000, 13.5000, 18.9000, 20.0000, 21.0000, 24.7000, 30.8000,
        34.9000, 26.6000, 25.3000, 24.7000, 21.2000, 19.3000, 20.0000, 16.6000,
        14.4000, 19.4000, 19.7000, 20.5000, 25.0000, 23.4000, 18.9000, 35.4000,
        24.7000, 31.6000, 23.3000, 19.6000, 18.7000, 16.0000, 22.2000, 25.0000,
        33.0000, 23.5000, 19.4000, 22.0000, 17.4000, 20.9000, 24.2000, 21.7000,
        22.8000, 23.4000, 24.1000, 21.4000, 20.0000, 20.8000, 21.2000, 20.3000,
        28.0000, 23.9000, 24.8000, 22.9000, 23.9000, 26.6000, 22.5000, 22.2000,
        23.6000, 28.7000, 22.6000, 22.0000, 22.9000, 25.0000, 20.6000, 28.4000,
        21.4000, 38.7000, 43.8000, 33.20

In [12]:
#Loss function

def mse(j1,j2):
    diff = j1-j2
    return torch.sum(diff**2)/diff.numel()

In [13]:
loss = mse(prediction, target)
print(loss)

tensor(388961.7338, dtype=torch.float64, grad_fn=<DivBackward0>)


In [14]:
loss.backward()

In [15]:
print(w)
print(w.grad)

tensor([[ 0.0956,  1.3336,  0.3277,  ...,  0.3446,  0.5403,  1.0686],
        [ 0.7557, -0.8195, -0.8813,  ...,  0.3163, -1.4882, -1.3397],
        [-0.4710,  1.0846,  0.7560,  ..., -0.0937, -1.0424, -0.8452],
        ...,
        [-0.5939,  0.7151,  0.9573,  ...,  0.1949, -1.9217, -1.5187],
        [-0.9152, -1.8962, -0.2293,  ...,  0.4306, -1.9058, -0.2595],
        [ 1.4194,  0.3418,  1.5563,  ..., -1.4213, -0.5029,  0.7592]],
       requires_grad=True)
tensor([[  -15.6304,   -13.4710,   -33.4145,  ...,   -44.9072,  -770.3875,
           -35.5370],
        [  -21.5109,   -51.5126,   -59.8656,  ...,   -93.2187, -1791.9105,
           -66.3631],
        [  -13.4179,   -30.5183,   -36.3239,  ...,   -56.7530, -1089.9917,
           -40.1374],
        ...,
        [    3.2868,   -16.1114,    -2.4861,  ...,   -12.2698,  -348.6987,
            -4.3987],
        [   -6.9185,   -36.9697,   -26.4636,  ...,   -47.5471,  -993.0109,
           -30.4506],
        [   -4.2505,   -12.3770,   -13.90

In [16]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [17]:
print(w)
print(b)

tensor([[ 0.0957,  1.3337,  0.3280,  ...,  0.3451,  0.5480,  1.0690],
        [ 0.7559, -0.8190, -0.8807,  ...,  0.3173, -1.4703, -1.3391],
        [-0.4708,  1.0849,  0.7564,  ..., -0.0932, -1.0315, -0.8448],
        ...,
        [-0.5939,  0.7153,  0.9574,  ...,  0.1950, -1.9182, -1.5187],
        [-0.9151, -1.8958, -0.2291,  ...,  0.4311, -1.8959, -0.2592],
        [ 1.4194,  0.3419,  1.5564,  ..., -1.4211, -0.4985,  0.7594]],
       requires_grad=True)
tensor([ 1.2213e+00, -2.2260e-01,  6.8552e-03, -1.4421e+00,  1.4083e+00,
        -6.0980e-01,  1.3713e+00,  2.4937e-01, -8.0962e-01,  8.1724e-01,
         1.3906e+00, -1.5578e+00, -8.6445e-01,  1.0228e+00,  1.3615e+00,
         1.3310e+00,  3.8060e-01, -8.0839e-02, -5.9589e-01, -3.9471e-01,
         1.9169e-01, -2.2260e-01, -2.1056e+00,  1.4557e+00,  8.7190e-01,
        -6.9053e-02,  2.7153e-01,  1.9213e+00,  5.8354e-01,  8.0199e-02,
        -2.9012e-01,  4.3031e-01, -1.4935e+00,  1.1464e+00, -8.6005e-01,
         5.3970e-01, -2.1590

In [18]:
# calcu;ating loss

prediction = model(input)
loss = mse(prediction, target)
print(loss)

tensor(379987.4844, dtype=torch.float64, grad_fn=<DivBackward0>)


In [19]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.

In [ ]:
# Train for multiple epochs

for i in range(100):
    preds = model(input)
    loss = mse(prediction, target)
    loss.backward(retain_graph = True)
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()